### ISSUE TITLE
Second round of sorted PRs

### ISSUE THREAD

**Issue by bstaletic** [YannickJadoul/pybind11-cleanup#3]
As discussed on gitter, I made a [gist](https://gist.github.com/bstaletic/b12ac9b7c8bba66d6f651d559c313362) with another 31 PR sorted, but not in the right format. I'll be away for the weekend, so I can't format this thing and merge it into the repo.

**Comment by eacousineau** [comment]
Any chance you've had a chance to formulate this? If not, I can take a whack at it.

**Comment by bstaletic** [comment]
I pushed a commit that resolves this. Closing.
